dependencies = [
    "scheme-basic",
    "latexmk",
    "koma-script",
    "hyperref",
    "calc",
    "multicol",
    "ifthen",
    "geometry",
    "amsmath",
    "tikz",
    "quantikz",
    "xargs",
    "xkeyval",
    "xstring",
    "mathtools",
    "environ",
    "tikz-cd",
]