name: Build

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: TeX-Live/setup-texlive-action@v3
        with:
          packages: |
            scheme-basic
            latexmk
            koma-script
            hyperref
            calc
            multicol
            ifthen
            geometry
            amsmath
            tikz
            quantikz
      - name: Setup Just
        uses: extractions/setup-just@v3
      - name: Build
        run: just build
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: 'main.pdf'
          path: out/main.pdf
